name: Docker Image Build

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/docker-image-mlc-llm-base.yml'
      - 'mlc-llm-rk3588/Dockerfile-base'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          DOCKER_BUILDKIT: "1"
        with:
          file: mlc-llm-rk3588/Dockerfile-base
          context: mlc-llm-rk3588
          push: true
          platforms: linux/arm64
          tags: vicalloy/mlc-llm-rk3588:base

