name: Docker Image Build

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/docker-image-python.yml'
      - 'Dockerfile-python.yml'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          DOCKER_BUILDKIT: "1"
        with:
          file: Dockerfile-python.yml
          push: true
          platforms: linux/arm/v7,linux/arm64
          tags: vicalloy/python:3.10
        allow: |
            security.insecure
