name: Docker Image Build

on:
  workflow_dispatch:
    inputs:
      model:
        description: 'ex: Llama-2-7b-chat-hf-q4f16_1'
      model-local-id:
        description: 'ex: FlagAlpha-Llama2-Chinese-7b-Chat-q4f16_1'


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          DOCKER_BUILDKIT: "1"
        with:
          # --build-arg bb=hello
          build-args: |
            MODEL=${{ github.event.inputs.model }}
            MODEL_LOCAL_ID=${{ github.event.inputs.model-local-id }}
          file: mlc-llm-rk3588/Dockerfile-base.yml
          push: true
          platforms: linux/arm64
          tags: vicalloy/mlc-llm-rk3588:${{ github.event.inputs.model-local-id }}

